#+TITLE: History

* Reference
- [[https://wellbay.cc/thread-1617166.htm][作業系統學習（一）-- 從發展史理解作業系統設計需求 ]]
* 1801: 卡片時代
- 1725年，法國紡織工人魯修為便於轉織圖樣，在織布機套上穿孔紙帶，他的合作夥伴則在1726年著手改良設計，將紙帶換成相互串連的穿孔卡片，以此達到僅需手工進料的半自動化生產。
- 1801年，法國人雅卡爾發明提花織布機，利用打孔卡控制織花圖樣，與前者不同的是，這部織布機變更連串的卡片時，無需更動機械設計，此乃可程式化機器的里程碑。
* 1835到1900年代：程式化計算機
- 1823年，英國數學家巴貝奇在政府的支持下，開始建造以蒸汽引擎驅動的差分機，用來比較數字間的差異，經歷10年未能竟功
* 1930到1960年代：桌上型計算器
- 1930年代，四則運算已經是桌上型機械計算器的基本功能，當時電腦的英文單字「Computer」指的是一群以操作數學計算器為業的「計算師」。
- 在曼哈頓計劃時期，許多精通微分方程式的女性數學家都擠在房間裡當起計算師報效祖國，後來的諾貝爾獎得主物理學家費曼先生還當過計算師主管。即使是名聞遐邇的波蘭數學家烏拉姆，在戰後也曾被利用來求取氫彈的數學似近值。
- 1948年，科塔計算器面市，這款機械式計算器造型輕便小巧，大小約莫有如一個胡椒粉研磨器。之後整個1950年代到1960年代，各種品牌相繼面市，爭奇鬥艷，好不熱鬧。
* 早期的數位電腦
- 1936年，在德國獨立研發的楚澤，開始打造以記憶能力和可程式化為特色的Z系列計算器。
- 楚澤後續機種Z3電腦完成於1941年，使用打孔膠捲作為輸入程式的媒介，以電話型繼電器為基礎，運作順利，因此成為首部可程式控制的功能性電腦。
- 二次大戰期間，英國在布萊切利園成功破解了部分德國軍事通訊密碼，在電機設計的炸彈機協助下，德軍的恩尼格瑪密碼機大受威脅，炸彈機是艾倫·圖靈與高登·威奇曼仿造1938年的波蘭解密機炸彈機所設計，運用一連串的電子邏輯演繹裝置找出可能是恩尼格瑪密碼機的密碼。
- 1939: 愛荷華州立大學的約翰·阿塔納索夫和克里夫·貝理開發出阿塔纳索夫貝理電腦（ABC），為一特殊用途的電子計算機，用以解決線性方程式的問題。ABC使用超過300個真空管提高運算速度，以固定在機械旋轉磁鼓上的電容器作為記憶裝置，雖然不可程式化，但是採用二進位制和電子線路等各方面，都使其成為第一部現代電腦的先驅。
- 1944: 1939年，馬克一號在IBM安迪卡特（Endicott）實驗室起手開發，雖然馬克一號被認為是第一部通用計算機，但其實並沒達到圖靈完全的條件。馬克一號後來移至哈佛大學，於1944年5月開機啟用。
  - 馬克一號的特點為全自動運算。一旦開始運算便無須人為介入。馬克一號是第一部被實作出來的全自動電腦，同時與當年的其他電子式電腦相比它非常可靠。大家認為「這是現代電腦時代的開端」以及「真正的電腦時代的曙光」。
  - One of the first programs to run on the Mark I was initiated on 29 March 1944[2] by John von Neumann. At that time, von Neumann was working on the Manhattan Project, and needed to determine whether implosion was a viable choice to detonate the atomic bomb that would be used a year later. The Mark I also computed and printed mathematical tables, which had been the initial goal of British inventor Charles Babbage for his "analytical engine".
  - The Mark I was disassembled in 1959, but portions of it were displayed in the Science Center as part of the Harvard Collection of Historical Scientific Instruments until being moved to the new Science and Engineering Complex in Allston in July 2021.[3] Other sections of the original machine were transferred to IBM and the Smithsonian Institution.

  - 馬克一號藉由打卡紙讀取、執行每一道指令。它沒有條件分支指令。這表示需要複雜運算的程式碼會很長一串。迴圈的完成需利用打卡紙頭尾相接的方式。這種程式碼與資料分開放置的架構就是眾所皆知的「哈佛架構」。計算機先驅葛麗絲·霍普是馬克一號的程式設計員。
- 1946: ENIAC的發展建造，始於1943年，1945年完工。設計剛發表時，不少研究人員認為這上千件脆弱的零件（像是真空管）會承受不住壓力損毀殆盡，導致ENIAC整天下線修整，一無事處。這也的確，但是每秒數千次的運算速度，只要零件故障前能跑上幾個鐘頭也算值回票價了。ENIAC是符合圖靈完全的裝置，「程式」對ENIAC來說，是一段電子程式儲存器到主機的距離，之間是由電纜和開關拼湊連接出來的運作狀態，不過在當時，光是能夠獨立運算這點，就已被認為是一大勝利5。
  - 給ENIAC程式設計的是六名女性。以目前的眼光來看，嚴格來說，那六名女性從事的工作並非是我們常說的程式設計師(當時只是用一個很廣泛的稱謂「程式設計師」來稱呼之而已）。一直要等馮紐曼提出他的電腦架構之後，才開始軟體這個概念。
  - ENIAC當時是一項複雜而復雜的技術。 它包含17,468個真空管以及70,000個電阻器，10,000個電容器，1,500個繼電器，6,000個手動開關和500萬個焊接接頭。 它的尺寸佔地面積為1,800平方英尺（167平方米），重達30噸，運行耗電160千瓦。 甚至有傳言說，一旦開機，費城市就會遭遇限電。 然而，1946年“費城公報”首次報導了這一謠言，此後一直被視為城市神話。
  - 在短短一秒內，ENIAC（比迄今為止任何其他計算機器快1000倍）可以執行5,000次增加，357次乘法或38次除法。 使用真空管代替開關和繼電器導致速度增加，但它不是一個快速重新編程的機器。 編程修改需要技術人員幾週的時間，而且機器總是需要長時間的維護。 作為一個側面說明，對ENIAC的研究導致了真空管的許多改進。
  - 1948年，John Von Neumann博士對ENIAC進行了多次修改。
  - ENIAC同時進行算術和轉換操作，這造成編程困難。 馮諾依曼建議可以使用開關來控制代碼選擇，以便可插拔電纜連接可以保持固定。 他添加了一個轉換器代碼來啟用串行操作。
  - ENIAC最初作為彈道計算，在每次運算前，必須根據運算要求、把不同的元件用人工插接線路的方式連接在一起。而這六位女性就是分析不同運算式，決定讓哪條電線連在哪個正確電路上。(這也是為何關於ENIAC的圖片幾乎全都是女性！)

* 首代范紐曼型架構及其機種
- 第一部成功運作的范紐曼型架構電腦是1948年曼徹斯特大學的小規模實驗機，又稱「寶貝」。隨後在1949年，曼切斯特1型電腦登場，功能完整，以威廉管和磁鼓作為記憶體媒介，並且引進索引暫存器的功能。
- 1947年，一家以飲料起家的英國餐飲公司約瑟·里昂公司，對新式的辦公室管理技術產生莫大的興趣，決定積極參與電腦的商業開發。到了1951年，里昂一號電腦起跑，執行了世上第一個辦公室電腦的例行指令。
- 1948年，John Von Neumann博士對ENIAC進行了多次修改。   
- 1949: EDVAC（電子離散變數自動計算機）和EDSAC（電子延遲儲存自動計算器）都於1949年完成。EDVAC是ENIAC的後繼產品。EDSAC是由劍橋大學計算實驗室的Maurice Wilkes領導的一個專案，基於EDVAC的建議而構建。兩者都是儲存程式的計算機：指令可以從計算機的記憶體中執行，而不是硬連線。他們使用了約翰·馮·諾依曼（John von Neumann）的體系結構，其中計算機的程式程式碼與資料駐留在同一儲存中。
- 951年11月，約瑟·里昂公司開始每週定期在里昂一號上，運作一支糕餅評估程式，這是第一支在程式儲存電腦上的商業應用程式。
- 1952年，IBM公開IBM 701電子資料處理器，是IBM 700/7000型系列的前鋒，也是IBM的第一部大型電腦。1954年推出IBM 704，所使用的磁芯記憶體後來成為大型電腦的標準配備。
- 1954：第一套可執行的一般用途高階程式語言FORTRAN也是在1955年到1956年間，IBM為IBM 704所開發的，並在1957年初發表6。
- 1955年，莫里斯·威爾克斯發明微程式設計，將基礎指令的程式內建，方便定義或延伸的工作7，廣泛運用在大型計算機（和其它諸如IBM 360系列的電腦）的中央處理器和浮點運算單元上。1956年，IBM首部磁碟儲存裝置統計控制隨機存取法（簡稱RAMAC）面市，使用50面24英吋的金屬磁碟，每面100道磁軌，總容量5MB，平均每MB需花費1萬美金。
* 電晶體電腦
- 1955: 第一台完全電晶體化的計算機是哈威爾·凱特或是IBM 604的原型機。Harwell CADET於1955年2月啟用，但它只能以58kHz的速度緩慢運作[來源請求]。寶萊公司（Burroughs Corporation）則聲稱，其於1957年6月交付給美國空軍，位於卡納維拉爾角飛彈靶場的SM-65 宇宙神（Atlas）洲際彈道飛彈/ THOR ABLE導航計算機（MOD 1）才是「世界上第一台可操作的電晶體計算機」[來源請求]。MIT的林肯實驗室也於1956年開始開發電晶體計算機「TX-0」。
- 1956: 作業系統: GM-NAA I/O，有記錄以來歷史上最早的計算機操作系統。美國通用汽車公司的羅伯特 L.帕特里克(Robert L.Patrick)和北美航空公司的Owen Mock共同設計。使之可以方便地訪問輸入輸出設備。這個系統的某些版本被用在多至40台IBM 704機器上。GM-NAA I/O可以成批的處理進程，在一項進程結束之後，它會自動的執行新的進程；它還可以集合存在相關數據與命令來產生並執行新的命令與任務；它還為程序提供了統一的共享介面，使之可以訪問電腦硬體的輸入輸出介面。
- 1956: UNIVAC 1103A，以中斷技術服務批次程式，為分時共享的先驅。
* 電晶體超級電腦
- 1964年發布的CDC 6600，被普遍被認為是第一台超級電腦[25][26]。CDC 6600的性能超過其前輩IBM 7030 Stretch約3倍。CDC 6600的性能約為1 megaFLOPS，1964年至1969年是世界上最快的電腦，後來它將這一地位讓給了其繼承者CDC 7600。
- IBM System/360: 作業系統OS/360
* 1960年代後：第三波
- 第三波電腦世代來臨，電腦使用度呈現爆炸性的成長，這些全仰賴傑克·基爾比和羅伯特·諾伊斯的獨立發明積體電路（或微晶片），引領英特爾的馬辛·霍夫和佛德里克·法金發明微處理器。在1960年代，大量的電腦技術和過去的第二波電腦世代重疊，直到1975年後期，第二波電腦世代的機器仍在持續量產，像是UNIVAC 494。
- 微電腦在1970年代初登場，到了1980年代後就已經成為家家戶戶都可看到的產品了。
- 第一款流行的個人電腦據信是出自蘋果電腦公司的創辦人之一史帝夫·沃茲尼克，不過他的第一部電腦Apple I出現得比KIM-1和Altair 8800晚，第一部具有圖形音效能力的蘋果電腦也晚於Commodore PET。
- 1980年代，家用計算機開始普及。通常此時的計算機擁有8-bit處理器加上64KB存儲器、顯示器、鍵盤以及低音質喇叭。
- 而80年代早期最著名的套裝計算機為使用微處理器6510（6502晶片特別版）的Commodore C64。此計算機沒有作業系統，而是以一8KB唯讀存儲器BIOS初始化彩色顯示器、鍵盤以及軟碟驅動器和印表機。它可用8KB唯讀存儲器BASIC語言來直接操作BIOS，並依此撰寫程式，大部分是遊戲。此BASIC語言的解釋器勉強可算是此計算機的作業系統，當然就沒有核心或軟硬體保護機制了。
- 此計算機上的遊戲大多跳過BIOS層次，直接控制硬體。
- 1969: UNIX
- 1978: Apple DOS 3.1 (Apple第一個OS)
- 1980: OS-9
- 1980: QDOS
- 1981: MS-DOS
- 1982: SunOS 1.0
- 1983: Novell NetWare
- 1984: Macintosh OS
- 1985: Microsoft Windows 1.0
- 1987: OS/2
- 1989: NeXTSTEP (1.0)
- 1990: Microsoft Windows 3.0
- 1991: Linux
- 1992: 386BSD 0.1
- 1992 Solaris 2.0
- 1993: FreeBSD
- 1995: Windows 95
- 1997: Mac OS 7.6 (Mac OS)
- 1998: Microsoft Windows 98
- 2000: Mac OS 9
- 2000: Microsoft Windows 2000
- 2001: Mac OS X 10.1
- 2001: Microsoft Windows XP
- 2009: Microsoft Windows 7
